# هذا الملف المسؤل عن المكتبة الخاصة بفلاتر

#---------------- اسم الملف والتفاصيل
name: malazim_iq
description: By hussein jabbar
#---------------- اسم الملف والتفاصيل

#---------------- اصدار فلاتر
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
#---------------- اصدار فلاتر

#---------------- ادوات ومكاتب
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  get_storage: ^2.0.3
  email_validator: ^2.0.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  intl_phone_number_input: ^0.7.0+2
  auto_size_text: ^3.0.0
  dio_http_cache: ^0.3.0
  select_form_field: ^2.2.0
  url_launcher: ^6.1.4
  flutter_svg: ^1.1.1+1
  cached_network_image: ^3.2.1
  favorite_button: ^0.0.4
  http: ^0.13.5
  flutter_cached_pdfview: ^0.4.1
  flutter_native_splash: ^2.2.8
  lazy_load_scrollview: ^1.3.0
  youtube_player_flutter: ^8.1.0
  loadmore: ^2.0.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  admob_flutter: ^3.0.0
  change_app_package_name: ^1.1.0
  app_tracking_transparency: ^2.0.2+4
 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  #----------- مكتبة ايقونات الخاصة بالتطبيق
  assets:
    - assets/logoSplash.png
    - assets/img/i.png
    - assets/more_icons/z1.png
    - assets/more_icons/z2.png
    - assets/more_icons/z3.png
    - assets/more_icons/z4.png
    - assets/more_icons/z5.png
    - assets/img/facebook.png
    - assets/img/instagram.png
    - assets/img/twitter.png
    - assets/img/profile_more.png
    - assets/img/about_img.png
    - assets/img/policyimg.png
    - assets/class_img/c1.png
    - assets/class_img/c2.png
    - assets/class_img/c3.png
    - assets/class_img/c4.png
    - assets/class_img/c5.png
    - assets/class_img/c6.png
    - assets/class_img/c7.png
    - assets/class_img/c8.png
    - assets/school_img/boy.png
    - assets/school_img/girl.png
    - assets/school_img/goup.png
    - assets/login/back_login.png
    - assets/login/darkbacLogin.png
    - assets/login/login.png
    - assets/login/loginEN.png
    - assets/login/Create.png
    - assets/login/CreateEN.png
    - assets/login/out.png
    - assets/login/outEN.png
    - assets/login/blacklogo.png
    - assets/login/whitelogo.png
    - assets/ads.png
    - assets/svg/search.svg
    - assets/svg/favourites.svg
    - assets/svg/followers.svg
    - assets/svg/Request.svg
    - assets/svg/Classroom.svg
    - assets/svg/News.svg
    - assets/svg/Results.svg
    - assets/svg/RequestDark.svg
    - assets/svg/Menus.svg
    - assets/svg/Appearance.svg
    - assets/svg/Change_Password.svg
    - assets/svg/Language.svg
    - assets/svg/Notification.svg
    - assets/svg/Modify_Profile.svg
    - assets/class_img/read.png

  #----------- مكتبة ايقونات الخاصة بالتطبيق

  fonts:
    - family: CairoSemiBold
      fonts:
        - asset: assets/CairoSemiBold.ttf
    - family: Cairo-Black
      fonts:
        - asset: assets/Cairo-Black.ttf
    - family: Cairo-Bold
      fonts:
        - asset: assets/Cairo-Bold.ttf
    - family: Cairo-ExtraLight
      fonts:
        - asset: assets/Cairo-ExtraLight.ttf
    - family: Cairo-Light
      fonts:
        - asset: assets/Cairo-Light.ttf
    - family: Cairo-Regular
      fonts:
        - asset: assets/Cairo-Regular.ttf
    - family: CairoSemiBold
      fonts:
        - asset: assets/CairoSemiBold.ttf
    - family: Cairo-SemiBold
      fonts:
        - asset: assets/Cairo-SemiBold.ttf
    - family: Cairo-SemiBold
      fonts:
        - asset: assets/Cairo-SemiBold.ttf
#---------------- ادوات ومكاتب
